### ISSUE TITLE
Remove Bourbon and Neat Dependencies

### ISSUE THREAD

**Issue by robneu** [wpsitecare/alpha#1]
We honestly don't use either of these for much at all anymore. Autoprefixer makes a lot of the mixins in Bourbon unnecessary and there are smaller libraries to handle the few things that we do use such as [Modular Scale](https://github.com/modularscale/modularscale-sass) and [media queries](http://paranoida.github.io/sass-mediaqueries/).

The one thing that would be a little difficult to replace is Neat. The only viable alternative I've found is [Flexbox Grid](http://flexboxgrid.com/) which has a [Sass version](https://github.com/kristoferjoseph/flexboxgrid/tree/sass) but it's still in development and hasn't been updated in a while.

We could roll our own grid system, but I'm not very familiar with flexbox and I've run into some performance issues with it on other builds.

**Comment by GaryJones** [comment]
I'm in agreement for my own projects too. 80% of Sass features I use are built-in to Sass, and much of this can be handled with PostCSS anyway. I've got one project that uses Neat, but otherwise barely touches Bourbon.

**Comment by robneu** [comment]
This is finished. I think I'll probably leave the actual node-neat package in our theme config to make working with projects which use the library a little easier. 

Some plugins, most notably WooCommerce, use Bourbon and Neat within their Sass files, so having it available can be useful sometimes.
