### ISSUE TITLE
No version specified for sitecare-theme-config in package.json (grunt shell not found)

### ISSUE THREAD

**Issue by jsiebach** [wpsitecare/alpha#7]
I just wanted to post this in case it helps someone.  When I cloned Alpha in the past it didn't specify a version of `sitecare-theme-config` in package.json.  When I recently updated a site it moved 2.1 to 3.1 and had some breaking changes.  I see package.json now specifies a version:

    "sitecare-theme-config": "wpsitecare/sitecare-theme-config#3.1.0",

If you have an issue (it might say `grunt-shell` not found) change

    "sitecare-theme-config": "wpsitecare/sitecare-theme-config",

to

    "sitecare-theme-config": "wpsitecare/sitecare-theme-config#2.1.0",

**Comment by robneu** [comment]
Sorry about this. The main reason a version was never specified is I was releasing changes to that config pretty rapidly for a while. I've never been able to figure out how to specify a version range for something that isn't hosted on npm, so I just opted for not setting one at all. 😕

**Comment by jsiebach** [comment]
No worries, I love the grunt set up you've built here!  I've adapted it to develop and package WP plugins as well, and used it as a guide to create a more general asset compilation pipeline for other projects.  Just wanted to put this here in case someone was having issues.

**Comment by robneu** [comment]
Sweet! I'm glad it's been useful for someone other than myself and my Site Care team members. I also maintain a [plugin version](https://github.com/wpsitecare/sitecare-plugin-config) that we use in a lot of the [plugins we build](https://github.com/wpsitecare/example-plugin) at Site Care. Feel free to take whatever you like from either of those. ❤️
